---
- name: Deploy and configure Zabbix agent
  hosts: zabbix_agents
  become: yes

  tasks:
    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: "{{ zabbix_agent_state }}"
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure Zabbix config directory exists
      file:
        path: "{{ zabbix_agent_config_path | dirname }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure Zabbix config file exists
      file:
        path: "{{ zabbix_agent_config_path }}"
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Configure Zabbix agent core settings
      lineinfile:
        path: "{{ zabbix_agent_config_path }}"
        regexp: '^{{ item.key }}='
        line: '{{ item.key }}={{ item.value }}'
        backup: yes
      loop:
        - { key: 'Server', value: '{{ zabbix_server_ip }}' }
        - { key: 'ServerActive', value: '{{ zabbix_server_ip }}' }
        - { key: 'Hostname', value: '{{ inventory_hostname }}' }

    - name: Ensure Zabbix agent is enabled and restarted
      systemd:
        name: "{{ zabbix_agent_service }}"
        enabled: yes
        state: restarted
